python -m collector --config TwitterAccount5 "Eric Bledsoe"
python -m collector --config TwitterAccount5 "LaMarcus Aldridge"
python -m collector --config TwitterAccount5 "Brandon Roy"
python -m collector --config TwitterAccount5 "Nicolas Batum"
python -m collector --config TwitterAccount5 "Rudy Gay"
python -m collector --config TwitterAccount5 "DeMarcus Cousins"
python -m collector --config TwitterAccount5 "Tony Parker"
python -m collector --config TwitterAccount5 "Tim Duncan"
python -m collector --config TwitterAccount5 "Kyle Lowry"
python -m collector --config TwitterAccount5 "Gordon Hayward"
python -m collector --config TwitterAccount5 "Derrick Favors"
python -m collector --config TwitterAccount5 "John Wass"
python -m collector --config TwitterAccount5 "Nene"
python -m collector --config TwitterAccount5 "Marcin Gortat"
